services:
  acestream:
    tmpfs: /dev/disk/by-id:noexec,rw,size=4k
    build: .
    container_name: acestream
    restart: unless-stopped
    ports:
      - 6878:6878
    environment:
      - INTERNAL_IP=127.0.0.1
      - HTTP_PORT=6878
      - HTTPS_PORT=6879
networks:
  default:
    driver: bridge
